/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADOIII;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andreson
 */
public class CadastroLivrosEditora extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLivrosEditora
     */
    public CadastroLivrosEditora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        cadEditora = new javax.swing.JPanel();
        lblNomeEditora = new javax.swing.JLabel();
        txtNomeEditora = new javax.swing.JTextField();
        btnSalvarEditora = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        cadLivros = new javax.swing.JPanel();
        txtNomeLivro = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        lblNomeLivro = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        cbCateg = new javax.swing.JComboBox<>();
        lblCateg = new javax.swing.JLabel();
        lblPag = new javax.swing.JLabel();
        txtPag = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbnSalavarLivros = new javax.swing.JButton();
        cbEditora = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLivros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuEditoras = new javax.swing.JMenuItem();
        menuLivros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.CardLayout());

        cadEditora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNomeEditora.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblNomeEditora.setText("Nome");

        btnSalvarEditora.setText("Cadastrar");
        btnSalvarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadEditoraLayout = new javax.swing.GroupLayout(cadEditora);
        cadEditora.setLayout(cadEditoraLayout);
        cadEditoraLayout.setHorizontalGroup(
            cadEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadEditoraLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(cadEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadEditoraLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNomeEditora)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cadEditoraLayout.createSequentialGroup()
                        .addGroup(cadEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cadEditoraLayout.createSequentialGroup()
                                .addComponent(lblInfo)
                                .addGap(0, 517, Short.MAX_VALUE))
                            .addGroup(cadEditoraLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(cadEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalvarEditora))))
                        .addContainerGap(105, Short.MAX_VALUE))))
        );
        cadEditoraLayout.setVerticalGroup(
            cadEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadEditoraLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblNomeEditora)
                .addGap(18, 18, 18)
                .addComponent(txtNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnSalvarEditora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(lblInfo)
                .addContainerGap())
        );

        panelPrincipal.add(cadEditora, "tela1");

        cadLivros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadLivros.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        lblNomeLivro.setText("Nome");

        lblAutor.setText("Autor");

        cbCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Aventura", "Drama", "Romance", "Terror", "Comédia", "Biografia", "Didático" }));

        lblCateg.setText("Categoria");

        lblPag.setText("Nº de Paginas");

        jLabel5.setText("Editoras");

        tbnSalavarLivros.setText("Cadastrar");
        tbnSalavarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnSalavarLivrosActionPerformed(evt);
            }
        });

        cbEditora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditoraActionPerformed(evt);
            }
        });

        jtLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Autor", "Categoria", "Nº Pag.", "Editora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtLivros);

        javax.swing.GroupLayout cadLivrosLayout = new javax.swing.GroupLayout(cadLivros);
        cadLivros.setLayout(cadLivrosLayout);
        cadLivrosLayout.setHorizontalGroup(
            cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadLivrosLayout.createSequentialGroup()
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cbCateg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135))
                    .addGroup(cadLivrosLayout.createSequentialGroup()
                        .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadLivrosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadLivrosLayout.createSequentialGroup()
                                .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(cadLivrosLayout.createSequentialGroup()
                        .addComponent(lblAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCateg)
                        .addGap(191, 191, 191))
                    .addGroup(cadLivrosLayout.createSequentialGroup()
                        .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadLivrosLayout.createSequentialGroup()
                                .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPag)
                                    .addComponent(txtPag, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblNomeLivro))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadLivrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbnSalavarLivros)
                .addContainerGap())
        );
        cadLivrosLayout.setVerticalGroup(
            cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadLivrosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblNomeLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(lblCateg))
                .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadLivrosLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel5))
                    .addGroup(cadLivrosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(lblPag)
                        .addGap(1, 1, 1)
                        .addGroup(cadLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(tbnSalavarLivros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        panelPrincipal.add(cadLivros, "tela2");

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setText("Cadastro");

        menuEditoras.setText("Editoras");
        menuEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditorasActionPerformed(evt);
            }
        });
        jMenu1.add(menuEditoras);

        menuLivros.setText("Livros");
        menuLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLivrosActionPerformed(evt);
            }
        });
        jMenu1.add(menuLivros);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditorasActionPerformed
        CardLayout c1 = (CardLayout) panelPrincipal.getLayout();
        c1.show(panelPrincipal, "tela1");
    }//GEN-LAST:event_menuEditorasActionPerformed

    private void menuLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLivrosActionPerformed
        // TODO add your handling code here:
        CardLayout  c1 = (CardLayout) panelPrincipal.getLayout();
        c1.show(panelPrincipal, "tela2");
    }//GEN-LAST:event_menuLivrosActionPerformed

    private void btnSalvarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditoraActionPerformed
        ArrayList <String> editora = new ArrayList<String>();
        editora.add(txtNomeEditora.getText());
        
        for(String nome:editora){
            cbEditora.addItem(nome);
        }
        lblInfo.setText("Salvo");
    }//GEN-LAST:event_btnSalvarEditoraActionPerformed

    private void cbEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditoraActionPerformed
        cbEditora.addItem(getName());
    }//GEN-LAST:event_cbEditoraActionPerformed

    private void tbnSalavarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnSalavarLivrosActionPerformed
        DefaultTableModel dtmLivros = (DefaultTableModel) jtLivros.getModel();
        String[] dados = {txtNomeLivro.getText(),txtAutor.getText(),cbCateg.getSelectedItem().toString(),
            txtPag.getText(),cbEditora.getSelectedItem().toString()};
        dtmLivros.addRow(dados);
    }//GEN-LAST:event_tbnSalavarLivrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivrosEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivrosEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivrosEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivrosEditora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivrosEditora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarEditora;
    private javax.swing.JPanel cadEditora;
    private javax.swing.JPanel cadLivros;
    private javax.swing.JComboBox<String> cbCateg;
    private javax.swing.JComboBox<String> cbEditora;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtLivros;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCateg;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNomeEditora;
    private javax.swing.JLabel lblNomeLivro;
    private javax.swing.JLabel lblPag;
    private javax.swing.JMenuItem menuEditoras;
    private javax.swing.JMenuItem menuLivros;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton tbnSalavarLivros;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtNomeEditora;
    private javax.swing.JTextField txtNomeLivro;
    private javax.swing.JTextField txtPag;
    // End of variables declaration//GEN-END:variables
}
